### PR TITLE
Update CDEPS to include the GFS_HAFS datamode

### PR DESCRIPTION
**Pull request by binli2337**
### Description of changes
Add the GFS_HAFS datamode. This datamode can be used in HAFS-MOM6 system to provide forcings in the non-overlapped regions.
### Specific notes

CDEPS Issues Fixed: #54 

Testing performed: ufs-weather-model regression tests

### CODE REVIEW

**Comment by binli2337** [comment]
@BinLiu-NOAA Can you review this PR? Thanks.

**Comment by junwang-noaa** [comment]
The code changes look good to me. One question, will you sync this change back to the ESCOMP?

**Review by junwang-noaa — APPROVED** [review]

**Comment by binli2337** [comment]
@junwang-noaa, I will sync these changes to ESCOMP after new regression tests using the HAFS-MOM6-WW3 model are well tested.

**Comment by BinLiu-NOAA** [comment]
@binli2337 and @junwang-noaa, wondering if we could also ask @uturuncoglu's help to review this PR as well. Thanks!

**Comment by junwang-noaa** [comment]
Sure!

**Comment by uturuncoglu** [comment]
@binli2337 Maybe it is a basic question but what is the main difference between GFS and GFS_HAFS data modes. Are they using different datasets?

**Comment by zach1221** [comment]
Testing has been completed on the merged UFS-WM PR of 1741 and 1699 [here.](https://github.com/ufs-community/ufs-weather-model/pull/1699). We can start the merging process.

**Comment by DeniseWorthen** [comment]
@uturuncoglu @binli2337 I would also like to understand the need for a new gfs_hafs routine. Why wasn't it possible to modify the existing gfs routine for an optional new use case with HAFS?

**Comment by binli2337** [comment]
@DeniseWorthen @uturuncoglu For the GFS datamode, there are no momentum flux fields. The HAFS application needs the momentum flux fields for the ocean model in the non-overlapped regions. In the current HAFS application, the momentum flux fields are read by HYCOM. In the HAFS with MOM6, the momentum fluxes and other flux fields are read by CDEPS for the non-overlapped regions. The new GFS_HAFS data mode includes the momentum flux fields.

**Comment by binli2337** [comment]
@uturuncoglu The GFS datamode and GFS_HAFS datamode use different datasets. The grid used in the UFS datamode is 3072x1536 (nx_global=3072,ny_global=1536). The grid used in the UFS_HAFS datamode is 1440x721. The UFS-HAFS datasets will be used in the HAFS-MOM6 application.

**Comment by DeniseWorthen** [comment]
@binli2337 I guess I still don't understand why the existing gfs couldn't have been modified using a configurable logical such as ``if (case_name .eq. 'hafs') then....`` instead of duplicating most of the module. We do this sort of optional advertisement of fields in MOM6, CICE6 and WW3.

**Comment by binli2337** [comment]
@DeniseWorthen Yes, the existing gfs datamode can be modified for the HAFS application.  I will combine the GFS datamode and GFS_HAFS datamode into a single datamode. Thanks!

**Comment by BinLiu-NOAA** [comment]
Thanks, @binli2337! I agree with @uturuncoglu and @DeniseWorthen. It would be better if we can unify the GFS datamode and GFS_HAFS datamode into a single datamode (may through some if conditions). Much appreciated!

**Comment by uturuncoglu** [comment]
@binli2337 I think having extra variables is not important and they could be still supported by the same data mode even with different resolution since it is controlled by the namelist option and mesh file. Recently, I modified ERA5 mode (also used by HAFS) to cover different ERA5 dataset produced for land coupling. It is still in my development fork but I am planning to push it soon. So, I think same approach can be also used in this case. It is in the following link if you want to look at,

https://github.com/uturuncoglu/CDEPS/tree/feature/noahmp

Specifically this file,

https://github.com/uturuncoglu/CDEPS/blob/feature/noahmp/datm/datm_datamode_era5_mod.F90

**Pull request merged**
