### PR TITLE
Update CDEPS

### PR DESCRIPTION
**Pull request by uturuncoglu**
This PR aims to update CDEPS to support new data atmosphere configurations (with ERA5) of component land model.

### CODE REVIEW

**Review by binli2337 — APPROVED** [review]
looks good.

**Comment by junwang-noaa** [comment]
@uturuncoglu Are the changes in the ESCOMP yet?

**Review by junwang-noaa — APPROVED** [review]

**Comment by uturuncoglu** [comment]
@junwang-noaa No. This is up-to-date with NOAA fork and also ERA5 mode is not used by CESM at this point. The exiting ERA5 RTs are fine with this change.

**Comment by uturuncoglu** [comment]
I mean I updated with ESCOMP but not recently. If you want I could sync with ESCOMP again. I think that would be better.

**Comment by jkbk2004** [comment]
@binli2337 Can you merge this pr? All tests were done at weather model side.

**Comment by jkbk2004** [comment]
@junwang-noaa @DeniseWorthen can you merge this pr?

**Comment by DeniseWorthen** [comment]
I cannot merge in this repo.

**Comment by jkbk2004** [comment]
@binli2337 thanks for merging this pr!

**Pull request merged**
