### PR TITLE
sync CDEPS with ESCOMP

### PR DESCRIPTION
**Pull request by uturuncoglu**
### Description of changes
This PR aims to sync CDEPS NOAA-EMC fork with ESCOM to bring support for configurable source and destination mask, which required for regional HAFS configuration.

### Specific notes

Contributors other than yourself, if any: @binli2337 @BinLiu-NOAA @DeniseWorthen

CDEPS Issues Fixed (include github issue #): N/A

Are there dependencies on other component PRs (if so list): No

Are changes expected to change answers (bfb, different to roundoff, more substantial): No

Any User Interface Changes (namelist or namelist defaults changes): 
The two new optional namelist option is introduced to the ESMF config file: stream_src_mask and stream_dst_mask to control mask values. The deafest are zero which does not change the existing behavior. Additional code needs to be implemented if we want to support XML configuration files.

Testing performed (e.g. aux_cdeps, CESM prealpha, etc): Using both CESM and UFS

Hashes used for testing:

### CODE REVIEW

**Review by binli2337 — APPROVED** [review]
Looks good. Approved.

**Comment by DeniseWorthen** [comment]
@uturuncoglu If I compare this branch to ESCOMP/main, there are still changes related to the inline implementation (hafs data mode). So this PR brings in the latest ESCOMP + your inline changes to EMC. But another PR back to ESCOMP will be needed to add the inline feature at ESCOMP/CDEPS, right?

**Comment by uturuncoglu** [comment]
@DeniseWorthen In terms of changes related to CDEPS, they are already in ESCOMP. For CMEPS, we first need to merge CMEPS PR on ESCOMP and then there will be another PR in EMC side to bring those to NOAA-EMC CMEPS fork. I did not create that PR yet but if you want I could create. Of course that needs to be merged after we merge the CMEPS PR in ESCOMP side. I hope my answer is clear. Let me know if it is not and want me to create PR in NOAA CMEPS fork.

**Comment by DeniseWorthen** [comment]
Hm, if I look here 
https://github.com/ESCOMP/CDEPS/compare/main...uturuncoglu:CDEPS:feature/mask

There are changes to 4 files that your branch has relative to ESCOMP?

**Comment by uturuncoglu** [comment]
@DeniseWorthen okay. Let me double check.

**Comment by uturuncoglu** [comment]
@DeniseWorthen i think it normal to see these difference since you are comparing with ESCOMP and it does not have those data modes developed by NOAA. If you really want to push those to CDEPS ESCOMP we need to modify the cime interface to handle those under CESM. I did it when i introduce the ERA5 mode but not for others since I did not develop those. Anyway, I think we are fine.

**Comment by DeniseWorthen** [comment]
Ok, thanks. I understand.

**Comment by BinLiu-NOAA** [comment]
@uturuncoglu, @DeniseWorthen ,and @binli2337, it looks to me the PR branch: https://github.com/uturuncoglu/CDEPS/tree/feature/mask has not yet synced with the target branch: https://github.com/NOAA-EMC/CDEPS/tree/develop
I thought that is required before merging the PR, is this true?

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA We do not update subcomponents until we commit the update in UWM. So each UWM PR should pull from a feature branch for a subcomponent. Then we test in UWM and only when testing is complete we update the top of the subcomponents.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA We do not update subcomponents until we commit the update in UWM. So each UWM PR should pull from a feature branch for a subcomponent. Then we test in UWM and only when testing is complete we update the top of the subcomponents.

@DeniseWorthen, I understand.

The issue is @uturuncoglu 's feature/mask branch did not sync with his last set of changes committed into NOAA-EMC/CDEPS through PR #59. Here are differences (after syncing and solving conflicts by removing the duplicated code sections related to case('SIMPLE'): in datm/atm_comp_nuopc.F90):

https://github.com/uturuncoglu/CDEPS/compare/feature/mask...hafs-community:CDEPS:feature/mask

With the new updated hafs-community:CDEPS:feature/mask branch, @binli2337 was able to run the failed atm_cdeps_lnd_era5 RT now on Hera (after adding "stream_vectors01:          null" in tests/parm/datm.streams.era5.IN).

With that, I created the following PR (https://github.com/uturuncoglu/CDEPS/pull/1) into @uturuncoglu 's feature/mask branch. After he accepts this PR, then it should be good to go (Plus, I will update tests/parm/datm.streams.era5.IN accordingly as well).

Cheers!

**Comment by DeniseWorthen** [comment]
@BinLiu-NOAA I understand now. That's great you figured it out.

**Comment by BinLiu-NOAA** [comment]
> @BinLiu-NOAA I understand now. That's great you figured it out.

Thanks @DeniseWorthen! Glad it works now. Thanks for @binli2337 for all the discussions and testing!

**Comment by jkbk2004** [comment]
All tests are done at https://github.com/ufs-community/ufs-weather-model/pull/2028 @binli2337 can you merge this pr?

**Pull request merged**
