### PR TITLE
Unify gfs, cfsr, and gefs datm datamodes

### PR DESCRIPTION
**Pull request by NickSzapiro-NOAA**
### Description of changes
Code for gfs, cfsr, and gefs datm datamodes is very similar (just with different function names). This PR removes the duplicates. As gefs datm datamode is already in ESCOMP/CDEPS, gefs is retained here. Note that GFS, GEFS, CFSR, etc. input datasets are still handled via streams in the same way, just with datamode == 'GEFS'. Sunset gfs_hafs datamode no longer used.
### Specific notes

Contributors other than yourself, if any:

CDEPS Issues Fixed (include github issue #): https://github.com/NOAA-EMC/CDEPS/issues/64

Are there dependencies on other component PRs (if so list):

Are changes expected to change answers (bfb, different to roundoff, more substantial): bfb

Any User Interface Changes (namelist or namelist defaults changes): Remove gfs and cfsr datm datamodes. Use gefs instead

Testing performed (e.g. aux_cdeps, CESM prealpha, etc): UFS regression test suite

Hashes used for testing: See https://github.com/ufs-community/ufs-weather-model/pull/2389

### CODE REVIEW

**Comment by NickSzapiro-NOAA** [comment]
If datm_datamode_gfs_hafs_mod has been replaced with CDEPS inline functionality and not to be pushed to ESCOMP/CDEPS, maybe this would be a good place to sunset it @binli2337

**Comment by binli2337** [comment]
@NickSzapiro-NOAA Yes, it is time to remove the gfs_hafs data mode. Thanks!

**Review by binli2337 — COMMENTED** [review]
Looks good. I will approve this PR after the related ufs-weather-model PR is approved. Thanks!

**Comment by NickSzapiro-NOAA** [comment]
Hi @binli2337 , Jun reviewed and approved the ufs-weather-model PR

**Comment by zach1221** [comment]
@binli2337 following up here. Are you able to review this PR?

**Comment by zach1221** [comment]
@binli2337 this PR is ready for final review.

**Review by jkbk2004 — APPROVED** [review]

**Comment by jkbk2004** [comment]
looks like I don't have permission to merge. @DeniseWorthen @binli2337 can you merge this pr?

**Comment by NickSzapiro-NOAA** [comment]
@jkbk2004 merged into cdeps

**Pull request merged**
