### PR TITLE
Create cplhist mode for dice

### LINKED ISSUE #61: Create cplhist mode for dice
A coupler history datamode (cplhist) allows a data component to read coupler history data in place of running an active component. dice does not have one implemented. A new dice cplhist datamode is needed to facilitate more isolated development of an active ATM in UFS.

### PR DESCRIPTION
**Pull request by NickSzapiro-NOAA**
### Description of changes
A new dice_datamode_cplhist_mod is adapted from docn_datamode_cplhist_mod. 
Existing sst_constant_value namelist value is used in docn_datamode_cplhist_advance to handle SST units in K and C.

### Specific notes

Contributors other than yourself, if any:

CDEPS Issues Fixed (include github issue #): https://github.com/NOAA-EMC/CDEPS/issues/61

Are there dependencies on other component PRs (if so list):

Are changes expected to change answers (bfb, different to roundoff, more substantial): bfb for existing and new for new datamode

Any User Interface Changes (namelist or namelist defaults changes):

Testing performed (e.g. aux_cdeps, CESM prealpha, etc): UFS regression testing (https://github.com/ufs-community/ufs-weather-model/pull/2186)

Hashes used for testing: See https://github.com/ufs-community/ufs-weather-model/pull/2186

### CODE REVIEW

**Review by uturuncoglu — APPROVED** [review]
Thanks for adding this mode. It looks good to me. If you don't mind and add some information about the new coupling mode to `doc/source/dice.rst`. If we push these developments to ESCOMP/CDEPS we could generate the documentation over there. As I know there is no any change in the CIME interface. If it is easy to port from ocean or any similar data component it would be nice to add mods for CIME interface. I could see something that can be used in the following link: https://github.com/NOAA-EMC/CDEPS/blob/3d7067a523b8557058755289e4275f5f5c985daf/docn/cime_config/stream_definition_docn.xml#L178 but not sure about all the changes that are required. Maybe searching `cplhist` under `docs` directory could help.

**Comment by NickSzapiro-NOAA** [comment]
Thank you, @uturuncoglu. I will add documentation. 

For pushing to ESCOMP/CDEPS, I am unclear if I should make testing for this new datamode in CIME like the regression tests to be added for ufs-weather-model

**Comment by zach1221** [comment]
Hi, @binli2337 could you please review this CDEPS PR?

**Review by jkbk2004 — APPROVED** [review]

**Comment by FernandoAndrade-NOAA** [comment]
Testing on [#2186](https://github.com/ufs-community/ufs-weather-model/pull/2186) has completed successfully, please continue with merging this PR.

**Pull request merged**
